### ISSUE TITLE
Installation on Ubuntu 

### ISSUE THREAD

**Issue by vik-y** [amahi/platform#125]
I am trying to understand this project more closely but I'm a little confused. 

First of all, the installation process. I couldn't find information anywhere about support on Ubuntu. The installation method for Ubuntu as mentioned in the docs here http://docs.amahi.org/ubuntu-12.html doesn't work. 
```sh
wget http://u12.amahi.org/install-amahi
--2017-03-13 10:29:37--  http://u12.amahi.org/install-amahi
Resolving u12.amahi.org (u12.amahi.org)... 208.115.201.203
Connecting to u12.amahi.org (u12.amahi.org)|208.115.201.203|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-13 10:29:38 ERROR 404: Not Found
```

I couldn't find any packages also for installation in Ubuntu. 

After this I cloned the code and initialised the application for testing. I ran the app with simple "rails s" command and accessed the dashboard on "localhost:3000" but I was not able to install any apps or setup shares which makes sense because those things require root permission. I would like to document the whole process a little for ubuntu if you can provide some clarity.

**Comment by FransM** [comment]
Hi,
As far as I know the ubuntu version is not maintained any more.In any case: ubuntu 12.04 itself will get out of maintenance next month, so it is probably not wise to build a new product on.As far as u12.amahi.org concerns: I guess this has gone
For packages please talk to cpg.
Best regards, Frans

**Comment by vik-y** [comment]
@FransM 

Hi,
```
ubuntu 12.04 itself will get out of maintenance next month, so it is probably not wise to build a new product on.
```
Ubuntu 12.04 is gone but Ubuntu 16.04 LTS is there. Even if the package is not available I am willing to try to make the code work in it. 

```
As far as u12.amahi.org concerns: I guess this has gone
For packages please talk to cpg.
```
Thanks for the info. Docs should be updated.

**Comment by cpg** [comment]
We don't have any plans at the moment for ubuntu or Debian based release. However, if you feel like you can carry such a project (perhaps long tem), we can entertain a proposal for it.

**Comment by vik-y** [comment]
Alright. I am more interested in improving the existing system but I can also maintain the ubuntu packages.

**Comment by VikashKothary** [comment]
I understand that Ubuntu is no longer maintained however is it possible to get a copy of the install script before it was taken down?
