### ISSUE TITLE
assets from plugins are not loaded

### ISSUE THREAD

**Issue by cpg** [amahi/platform#181]
seeing a few errors like this, indicating the assets from the plugins are not loaded at all:
```
ActionController::RoutingError (No route matches [GET] "/javascripts/settings.js")
```

**Comment by sukhbir-singh** [comment]
on branch rails-5-2 and r52-b4, I am not able to reproduce this bug. This bug probably has occurred because of some missing js include statements, which now included in respective view files. If someone could reproduce this bug, that might be helpful to solve this if the bug is still present.

**Comment by cpg** [comment]
With asset precompilation it looks like this is not happening, though plugins are installed dynamically, so this may not be the end of it.
