### ISSUE TITLE
no password is asked when creating hda_development db using 'rake db:migrate'

### ISSUE THREAD

**Issue by Batey96** [amahi/platform#224]
Due to this a mysql login error is a given.To solve this,the /path/to/database.yml file is manually edited to change the default msyql password from amahi to realmysql password.This is time consuming in the development platform

**Comment by cpg** [comment]
Different platforms (mac, linux, other ..) as well as different mysql distributions (mariadb, official mysql, realmysql? ..) and each person's local configuration may have different settings. So this is hard to make common.

Also, it should be a one-time change and no need to change again in development, so I am not sure I understand the reason it's time consuming.

In any case, without much detail, we can't really help ameliorate this situation. Please reopen if you have a suggestion (or create a PR).
